import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/auth/context';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { useChangePasswordMutation } from '@/store/services/api'; // Generate this export
import { toast } from 'sonner';
import { Eye, EyeOff } from 'lucide-react';

export function ChangePassword() {
    const [oldPassword, setOldPassword] = useState('');
    const [newPassword, setNewPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [showPassword, setShowPassword] = useState(false);

    // Use the mutation (Note: 'useChangePasswordMutation' will be auto-generated by RTK Query from 'changePassword' endpoint)
    // We need to cast it or assume it exists after api generation.
    // Since I added it to api.ts, I should be able to import it.
    // However, I need to check if 'useChangePasswordMutation' is exported. It usually is auto-exported.
    // I might need to manually add the export if api.ts doesn't export hooks automatically?
    // api.ts uses createApi... export const { ... } = api; 
    // I need to check api.ts export statement.
    const [changePassword, { isLoading }] = useChangePasswordMutation();
    const navigate = useNavigate();
    const { logout } = useAuth(); // If success, maybe logout or redirect to dashboard?

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (newPassword !== confirmPassword) {
            toast.error("New passwords do not match");
            return;
        }

        if (newPassword.length < 8) {
            toast.error("Password must be at least 8 characters");
            return;
        }

        try {
            await changePassword({ oldPassword, newPassword }).unwrap();

            toast.success("Password changed successfully. Please login again.");
            logout(); // Force re-login to update context purely
            navigate('/login');

        } catch (err: any) {
            toast.error(err?.data?.message || "Failed to change password");
        }
    };

    return (
        <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-4">
            <Card className="w-full max-w-md">
                <CardHeader>
                    <CardTitle>Change Password</CardTitle>
                    <CardDescription>You must change your password before proceeding.</CardDescription>
                </CardHeader>
                <CardContent>
                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div className="space-y-2">
                            <label className="text-sm font-medium">Current Password</label>
                            <input
                                type="password"
                                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                                value={oldPassword}
                                onChange={(e) => setOldPassword(e.target.value)}
                                required
                            />
                        </div>
                        <div className="space-y-2">
                            <label className="text-sm font-medium">New Password</label>
                            <div className="relative">
                                <input
                                    type={showPassword ? "text" : "password"}
                                    className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm pr-10"
                                    value={newPassword}
                                    onChange={(e) => setNewPassword(e.target.value)}
                                    required
                                />
                                <button
                                    type="button"
                                    onClick={() => setShowPassword(!showPassword)}
                                    className="absolute right-3 top-2.5 text-gray-500"
                                >
                                    {showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                                </button>
                            </div>
                        </div>
                        <div className="space-y-2">
                            <label className="text-sm font-medium">Confirm New Password</label>
                            <input
                                type="password"
                                className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
                                value={confirmPassword}
                                onChange={(e) => setConfirmPassword(e.target.value)}
                                required
                            />
                        </div>

                        <Button type="submit" className="w-full" disabled={isLoading}>
                            {isLoading ? "Changing Password..." : "Change Password"}
                        </Button>
                        <div className="text-center mt-2">
                            <button type="button" onClick={() => { logout(); navigate('/login'); }} className="text-sm text-gray-500 hover:text-gray-700">
                                Back to Login
                            </button>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </div>
    );
}
